### PR TITLE
Fix misaligned sprites

### PR DESCRIPTION
**Pull request by Anthcny144**
Fix certain sprites being off by a pixel, and made the Chomp's eyes black instead of transparent

### CODE REVIEW

**Comment by tmalahie** [comment]
Nice, thanks for the PR 👍 I'll take a look later

**Comment by VulpixTails** [comment]
Hello, can you add the fixed Peach/Daisy kart sprite, as I made it smoother!
IMG_0069
IMG_0070

**Comment by Anthcny144** [comment]
Hello! What exactly is different from the current sprites? You should make a request showcasing the older and newer ones on the Discord if possible, so people can decide which one to keep

**Comment by VulpixTails** [comment]
These are the old/current sprites which have the first, twelfth and turning sprite one pixel lower
IMG_0072
IMG_0073

**Comment by Anthcny144** [comment]
The current sprites are good, the ones you made have missing pixels on the crown. The current sprites are not misaligned in any way

**Comment by tmalahie** [comment]
Hey 👋
Yeah I don't see the issue with Daisy & Peach sprites either, if you really think there is maybe you can explain & submit the changes in another PR @VulpixTails ?

**Comment by tmalahie** [comment]
About your PR @Anthcny144 I tested it and I think the changes are good 👍 thanks again for submitting it
There's just one thing, I don't see the changes in the chomp sprites, for me the 2 files look the same but maybe I'm just blind 😄

**Comment by Anthcny144** [comment]
My bad I pushed the wrong one 😆 The new one has black eyes instead of transparent eyes, it was requested on the Discord

**Review by tmalahie — APPROVED** [review]

**Pull request merged**
